Update to 6.0.0

diff --git a/6.0/Dockerfile.native b/6.0/Dockerfile.native
--- a/6.0/Dockerfile.native
+++ b/6.0/Dockerfile.native
@@ -21,11 +21,13 @@ RUN set -eux; \
 		echo 'Pin-Priority: -10'; \
 	} > /etc/apt/preferences.d/qemu.pref; \
 	apt-get update; \
-	apt-get install -y --no-install-recommends \
-		ovmf \
-		qemu-efi-aarch64 \
-		qemu-efi-arm \
-	; \
+	arch="$(dpkg --print-architecture)"; \
+	case "$arch" in \
+		amd64) apt-get install -y --no-install-recommends ovmf ;; \
+		arm64) apt-get install -y --no-install-recommends qemu-efi-aarch64 ;; \
+		armel | armhf) apt-get install -y --no-install-recommends qemu-efi-arm ;; \
+		*) echo >&2 "warning: architecture '$arch' unknown 😅 (is there a 'QEMU firmware' package that should be installed here? likely candidates: https://packages.debian.org/source/$suite/edk2)" ;; \
+	esac; \
 	rm -rf /var/lib/apt/lists/*
 
 COPY *.patch /qemu-patches/
@@ -38,8 +40,8 @@ ENV QEMU_KEYS \
 
 # https://www.qemu.org/download/#source
 # https://download.qemu.org/?C=M;O=D
-ENV QEMU_VERSION 4.2.1
-ENV QEMU_URL https://download.qemu.org/qemu-4.2.1.tar.xz
+ENV QEMU_VERSION 6.0.0
+ENV QEMU_URL https://download.qemu.org/qemu-6.0.0.tar.xz
 
 RUN set -eux; \
 	\
@@ -82,6 +84,9 @@ RUN set -eux; \
 		python3 \
 		xfslibs-dev \
 		zlib1g-dev \
+# https://wiki.qemu.org/ChangeLog/5.2#Build_Information
+		ninja-build \
+		python3-setuptools \
 	; \
 	rm -rf /var/lib/apt/lists/*; \
 	\
@@ -108,17 +113,23 @@ RUN set -eux; \
 	done; \
 	rm -rf /qemu-patches; \
 	\
+	arch="$(dpkg --print-architecture)"; \
+	case "$arch" in \
+		amd64) targetList='x86_64-softmmu' ;; \
+		arm64) targetList='aarch64-softmmu' ;; \
+		armel | armhf) targetList='arm-softmmu' ;; \
+		i386) targetList='i386-softmmu' ;; \
+		mips64el) targetList='mips64el-softmmu' ;; \
+		ppc64el) targetList='ppc64-softmmu' ;; \
+		s390x) targetList='s390x-softmmu' ;; \
+		*) echo >&2 "error: architecture '$arch' unimplemented 😅"; exit 1 ;; \
+	esac; \
+	\
 	./configure --help; \
 	./configure \
 # let's add a link to our source code in the output of "--version" in case our users end up filing bugs against the QEMU project O:)
 		--with-pkgversion='https://github.com/tianon/docker-qemu' \
-		--target-list=' \
-# system targets
-# (https://sources.debian.org/src/qemu/buster/debian/rules/#L59-L63, slimmed)
-			i386-softmmu x86_64-softmmu aarch64-softmmu arm-softmmu m68k-softmmu \
-			mips64-softmmu mips64el-softmmu ppc64-softmmu riscv64-softmmu \
-			sparc64-softmmu s390x-softmmu \
-		' \
+		--target-list="$targetList" \
 # let's point "firmware path" to Debian's value so we get access to "OVMF.fd" and friends more easily
 		--firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu \
 # https://salsa.debian.org/qemu-team/qemu/-/blob/058ab4ec8623766b50055c8c56d0d5448d52fb0a/debian/rules#L38
